Blogger/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path
from accounts.views import CreateUserView, SignInUserView, SignOutView, UserEditView

app_name = "accounts"

urlpatterns = [
    path('signup/', CreateUserView.as_view(), name="signup"),
    path('signin/', SignInUserView.as_view(), name="signin"),
    path('signout/', SignOutView.as_view(), name="signout" ),
    path('profile/update', UserEditView.as_view(), name="update" ),
    
]

core/urls.py
from django.urls import path
from core.views import (HomeListView, 
                        CreatePostView, 
                        DetailPostView, 
                        UpdatePostView, 
                        DeletePostView,
                        MyProfileView,
                        OtherUserProfileView)
app_name = "core"

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('create', CreatePostView.as_view(), name='create'),
    path('myprofile', MyProfileView.as_view(), name='myprofile'),
    path('profile/<int:user_id>/', OtherUserProfileView.as_view(), name='profile'),
    path('detail/<int:pk>', DetailPostView.as_view(), name='detail'),
    path('update/<int:pk>', UpdatePostView.as_view(), name='update'),
    path('delete/<int:pk>', DeletePostView.as_view(), name='delete'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    publish = models.BooleanField(blank=True, default=False)

    def __str__(self):
        return self.title

core/forms.py
from django import forms
from core.models import Post

class UpdateForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 'content', 'publish']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'content': forms.Textarea(attrs={'class':'form-control'}),
            'publish': forms.CheckboxInput(),
        }
class CreateForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 'content', 'publish']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'content': forms.Textarea(attrs={'class':'form-control'}),
            'publish': forms.CheckboxInput(),
        }

core/views.py
from core.models import Post
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from core.forms import CreateForm, UpdateForm
from django.contrib.auth.mixins import (LoginRequiredMixin, 
                                        UserPassesTestMixin)
from django.views.generic import (CreateView, 
                                  DetailView, 
                                  DeleteView,
                                  ListView,
                                  UpdateView)


class HomeListView(ListView):
    
    model = Post
    template_name = "core/home.html"
    
    def get_queryset(self):
        return Post.objects.filter(publish=True)
    

class MyProfileView(LoginRequiredMixin, ListView):
    
    model = Post
    template_name = "core/my_profile.html"
    
    def get_queryset(self):
        return Post.objects.filter(user=self.request.user)
    
class OtherUserProfileView(LoginRequiredMixin, ListView):

    model = Post
    template_name = "core/otheruser.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user_id=self.kwargs['user_id'])
        return queryset
    
    
class CreatePostView(LoginRequiredMixin, CreateView):
    
    model = Post
    template_name = "core/create.html"
    form_class = CreateForm
    success_url = "/"
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CreatePostView, self).form_valid(form)
    
    
class DetailPostView(LoginRequiredMixin, DetailView):
    
    model = Post
    template_name = "core/detail.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
    
class UpdatePostView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    
    model = Post
    template_name = "core/update.html"
    form_class = UpdateForm
    success_url = '/'
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.user:
            return True
        return False
    

class DeletePostView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    
    model = Post
    template_name = "core/delete.html"
    success_url = "/"
    
    def get_object(self):
        pk_ = self.kwargs.get("pk")
        return get_object_or_404(Post, pk=pk_)
    
    def get_success_url(self):
        return reverse("core:home")
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.user:
            return True
        return False

core/templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary mb-5">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Blogger</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">My Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Users</a>
            </li>
            <a class="nav-link" href="#">Annoucement</a>
          </li>
            </li>
              <a class="nav-link" href="#">About</a>
            </li>
          </ul>
          
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signout' %}">Logout</a>
            </li>
              {%else%}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'accounts:signin' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">Sign-up</a>
              </li>
              {% endif %}
            </ul>
        </div>
      </div>
    </nav>

 
    {% block content%}
    {% endblock %}


  </body>
</html>

core/templates/core/create.html
{% extends 'core/base.html' %}
{% block content%}
<div class="container pt-5">
    <div class="form-control">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p}}
            <button type="submit" class="btn btn-success">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

core/templates/core/delete.html
{% extends 'core/base.html' %}
{% block content %}
<div class="container">
    <div class="card w-75">
        <div class="card-body">
            <form method="POST">
                <h5 class="card-title">Delete Post!</h5>
                <p class="card-text">Would you like to delete this object.</p>
                <button class="btn btn-danger" type="submit">Delete</button>
                <a href="{% url 'core:home'%}" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}



  

core/templates/core/detail.html
{% extends 'core/base.html' %}
{% block content%}
<form method="POST">
    {% csrf_token  %}
    <div class="container shadow bg-secondary text-light" style="max-width: 70rem;">
    <figure>
        <blockquote class="blockquote">
            <cite title="Source Title pb-1"><h2 class="py-3">{{object.title}}</h2></cite>
            <p class="mb-4">{{object.content}}</p>
            <h5>Published: {{object.publish}}</h5>
            <h6>{{object.created}}</h6>
        </blockquote>
        <h3 class="my-4"><figcaption class="blockquote-footer">
            {{object.user}}
        </figcaption></h3>
    </figure>
    <a href="{% url 'core:delete' object.pk %}" class="btn btn-danger mb-2"><h5>Delete</h5></a>
    <a href="{% url 'core:update' object.pk %}" class="btn btn-primary mb-2"><h5>Update</h5></a>
</form>
</div>
{% endblock %}

core/templates/core/home.html
{% extends "core/base.html" %}

    {% block content%}
    {% for item in object_list%}
    <div class="container">
    <div class="card text-light bg-secondary mb-3 mx-auto" style="max-width: 60rem;">
        <div class="card-header text-light">{{item.title}}</div>
        <div class="card-body">
        <p class="card-text text-light">{{item.content}}</p>
        <h6 class="card-title text-light"><a class="text-light" href="{% url 'core:detail' item.pk %}">Full Page</a></h6>
        <p class="card-text text-light"><a class="text-light " href="{% url 'core:profile' user_id=item.user_id %}">{{item.user}}</a><small class="text-light"> {{item.created}} </small></p>
        </div>
    </div>
    </div>
    {% endfor%}
    {% endblock %}

core/templates/core/my_profile.html
{% extends "core/base.html" %}

    {% block content%}
    {% for item in object_list%}
    <div class="container">
    <div class="card text-light bg-secondary mb-3 mx-auto" style="max-width: 60rem;">
        <div class="card-header text-light">{{item.title}}</div>
        <div class="card-body">
        <p class="card-text text-light">{{item.content}}</p>
        <h6 class="card-title text-light"><a class="text-light" href="{% url 'core:detail' item.pk %}">Full Page</a></h6>
        <p class="card-text text-light"><small class="text-light"><a href="">{{item.user}}</a> {{item.created}} </small></p>
        </div>
    </div>
</div>
    {% endfor%}
    {% endblock %}

core/templates/core/otheruser.html
{% extends 'core/base.html' %}
{% block content %}
{% for user in object_list%}
    {{user.title}}
{% endfor %}
{% endblock %}

core/templates/core/update.html
{% extends 'core/base.html' %}
{% block content%}
<div class="container pt-5">
    <div class="form-control">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p}}
            <button type="submit" class="btn btn-success">Done</button>
        </form>
    </div>
</div>
{% endblock %}